// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using SiteOfRefuge.API;

namespace SiteOfRefuge.API.Models
{
    /// <summary> The method in which this person can be contacted. </summary>
    public partial class ContactMode
    {
        public ContactMode() {}
        
        /// <summary> Initializes a new instance of ContactMode. </summary>
        /// <param name="method"> The actual way to contact this person. </param>
        /// <param name="value"> The details on how to contact this person (actual phone number, email address etc). </param>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public ContactMode(ContactModeMethod method, string value)
        {
            if (value == null)
            {
                throw new ArgumentNullException(nameof(value));
            }

            Method = method;
            Value = value;
        }

        /// <summary> Initializes a new instance of ContactMode. </summary>
        /// <param name="id"> Unique identifier in UUID/GUID format. </param>
        /// <param name="method"> The actual way to contact this person. </param>
        /// <param name="value"> The details on how to contact this person (actual phone number, email address etc). </param>
        /// <param name="verified"> Has this contact method been verified?. </param>
        internal ContactMode(Guid? id, ContactModeMethod method, string value, bool? verified)
        {
            Id = id;
            Method = method;
            Value = value;
            Verified = verified;
        }

        /// <summary> Unique identifier in UUID/GUID format. </summary>
        public Guid? Id { get; set; }
        /// <summary> The actual way to contact this person. </summary>
        public ContactModeMethod Method { get; set; }
        /// <summary> The details on how to contact this person (actual phone number, email address etc). </summary>
        public string Value { get; set; }
        /// <summary> Has this contact method been verified?. </summary>
        public bool? Verified { get; set; }
    }
}
