// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using SiteOfRefuge.API;

namespace SiteOfRefuge.API.Models
{
    /// <summary> Summary of a Host. </summary>
    public partial class HostSummary
    {
        public HostSummary() { } 
        
        /// <summary> Initializes a new instance of HostSummary. </summary>
        /// <param name="id"> Unique identifier in UUID/GUID format. </param>
        /// <param name="region"> The region where the person is located. This is in ISO 3166-2 format. </param>
        /// <param name="allowedPeople"> . </param>
        /// <param name="shelter"> . </param>
        /// <param name="availability"> . </param>
        /// <exception cref="ArgumentNullException"> <paramref name="region"/>, <paramref name="shelter"/>, or <paramref name="availability"/> is null. </exception>
        public HostSummary(Guid id, string region, int allowedPeople, string shelter, Availability availability)
        {
            if (region == null)
            {
                throw new ArgumentNullException(nameof(region));
            }
            if (shelter == null)
            {
                throw new ArgumentNullException(nameof(shelter));
            }
            if (availability == null)
            {
                throw new ArgumentNullException(nameof(availability));
            }

            Id = id;
            Region = region;
            AllowedPeople = allowedPeople;
            Restrictions = new List<Restrictions>();
            Shelter = shelter;
            Languages = new List<SpokenLanguages>();
            Availability = availability;
        }

        /// <summary> Initializes a new instance of HostSummary. </summary>
        /// <param name="id"> Unique identifier in UUID/GUID format. </param>
        /// <param name="region"> The region where the person is located. This is in ISO 3166-2 format. </param>
        /// <param name="allowedPeople"> . </param>
        /// <param name="restrictions"> Any restrictions the host has for this shelter. </param>
        /// <param name="message"> A freeform text field that allows for a personalized message. </param>
        /// <param name="shelter"> . </param>
        /// <param name="languages"> . </param>
        /// <param name="availability"> . </param>
        internal HostSummary(Guid id, string region, int allowedPeople, IList<Restrictions> restrictions, string message, string shelter, IList<SpokenLanguages> languages, Availability availability)
        {
            Id = id;
            Region = region;
            AllowedPeople = allowedPeople;
            Restrictions = restrictions;
            Message = message;
            Shelter = shelter;
            Languages = languages;
            Availability = availability;
        }

        /// <summary> Unique identifier in UUID/GUID format. </summary>
        public Guid Id { get; set; }
        /// <summary> The region where the person is located. This is in ISO 3166-2 format. </summary>
        public string Region { get; set; }
        public int AllowedPeople { get; set; }
        /// <summary> Any restrictions the host has for this shelter. </summary>
        public IList<Restrictions> Restrictions { get; }
        /// <summary> A freeform text field that allows for a personalized message. </summary>
        public string Message { get; set; }
        public string Shelter { get; set; }
        public IList<SpokenLanguages> Languages { get; }
        public Availability Availability { get; set; }
    }
}
