// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.Extensions.Logging;

namespace SiteOfRefuge.API
{
    public class SearchApi
    {
        /// <summary> Initializes a new instance of SearchApi. </summary>
        public SearchApi() {}

        /// <summary> Attempt to find hosts that match the needs of a refugee. This id has to match with the id in the access token. </summary>
        /// <param name="req"> Raw HTTP Request. </param>
        /// <param name="id"> Refugee id in UUID/GUID format. </param>
        [Function(nameof(FindMatch))]
        public HttpResponseData FindMatch([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "search/{id}")] HttpRequestData req, Guid id, FunctionContext context)
        {
            var logger = context.GetLogger(nameof(FindMatch));            
            logger.LogInformation("HTTP trigger function processed a request.");

            // TODO: Handle Documented Responses.
            // Spec Defines: HTTP 200
            // Spec Defines: HTTP 403
            // Spec Defines: HTTP 404

            throw new NotImplementedException();
        }
    }
}
